 version: "3.8"
   services:
     dim:
       container_name: dim
       image: vgarleanu/dim
       ports:
         - 8000:8000
       volumes:
         - /<host_config_folder>:/opt/dim/config
         - /<host_media_path>:/<container_media_path>
       #Use the below lines, to pass your device with hardware acceleration
       devices:
         - /<device>:/<device>
