[development]
address = "0.0.0.0"
port = 8000
log = "off"

[production]
address = "0.0.0.0"
port = 2550
log = "off"

[global.databases]
openflix = { url = "postgres://postgres:dimpostgres@127.0.0.1/dim" }
