DROP TABLE mediafile;
DROP TABLE episode;
DROP TABLE season;
DROP TABLE tv_show;
DROP TABLE movie;
DROP TABLE streamable_media;
DROP TABLE media CASCADE;
DROP TABLE library;
DROP TABLE progress;
DROP TABLE users;
DROP TABLE progress;
DROP TABLE genre_media;
DROP TABLE genre;
DROP TABLE invites;
