[package]
name = "events"
version = "0.1.0"
authors = ["Valerian G. <valerian.garleanu@pm.me>"]
edition = "2018"

[dependencies]
pushevent = { git = "https://github.com/vgarleanu/pushevent" }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
