/*
    * == USER ACTIONS ==
*/

// [GET] USER INFO
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_OK = "FETCH_USER_OK";
export const FETCH_USER_ERR = "FETCH_USER_ERR";

/*
    * == LIBRARY ACTIONS ==
*/

// [GET] ALL LIBRARIES
export const FETCH_LIBRARIES_START = "FETCH_LIBRARIES_START";
export const FETCH_LIBRARIES_OK = "FETCH_LIBRARIES_OK";
export const FETCH_LIBRARIES_ERR = "FETCH_LIBRARIES_ERR";

// [GET] LIBRARY INFO
export const FETCH_LIBRARY_INFO = "FETCH_LIBRARY_INFO";

// [GET] LIBRARY MEDIA
export const FETCH_LIBRARY_MEDIA = "FETCH_LIBRARY_MEDIA";

// [POST] NEW LIBRARY
export const NEW_LIBRARY = "NEW_LIBRARY";

// [DELETE] LIBRARY
export const DEL_LIBRARY = "DEL_LIBRARY";

/*
    * == HOST ACTIONS ==
*/

// [GET] ALL HOSTS
export const FETCH_HOSTS_START = "FETCH_HOSTS_START";
export const FETCH_HOSTS_OK = "FETCH_HOSTS_OK";
export const FETCH_HOSTS_ERR = "FETCH_HOSTS_ERR";

/*
    * == DASHBOARD ACTIONS ==
*/

// [GET] DASHBOARD MEDIA
export const FETCH_DASHBOARD_START = "FETCH_DASHBOARD_START";
export const FETCH_DASHBOARD_OK = "FETCH_DASHBOARD_OK";
export const FETCH_DASHBOARD_ERR = "FETCH_DASHBOARD_ERR";

// [GET] DASHBOARD BANNERS
export const FETCH_BANNERS_START = "FETCH_BANNERS_START";
export const FETCH_BANNERS_OK = "FETCH_BANNERS_OK";
export const FETCH_BANNERS_ERR = "FETCH_BANNERS_ERR";